spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hexagon_jct?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect 
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect 
 